nginx_vhosts:
  - listen: "80"
    server_name: "localhost"
    access_log: "/var/log/nginx/access.log"
    error_log: "/var/log/nginx/error.log"
    extra_parameters: |
      location / {
          proxy_pass http://127.0.0.1:8080;
      }
nginx_remove_default_vhost: true
nginx_vhosts_filename: "vhosts.conf"
nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main"
logrotate_scripts:
  - name: nginx
    path: /var/log/nginx/*.log
    options:
      - weekly
      - size 25M
      - rotate 7
      - missingok
      - compress
      - delaycompress
      - copytruncate
    scripts:
      postrotate: "[ -s /run/nginx.pid ] && kill -USR1 `cat /run/nginx.pid`"
