nginx_vhosts:
  - listen: "80"
    server_name: "dotstamp.com"
    access_log: "/var/log/nginx/access.log"
    error_log: "/var/log/nginx/error.log"
    extra_parameters: |
      location / {
          proxy_pass http://127.0.0.1:8080;
      }
nginx_remove_default_vhost: true
nginx_vhosts_filename: "vhosts.conf"
nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log "
logrotate_scripts:
  - name: nginx
    path: /var/log/nginx/*.log
    options:
      - weekly
      - size 25M
      - rotate 4
      - missingok
      - compress
      - delaycompress
      - copytruncate
    scripts:
      postrotate: "[ -s /run/nginx.pid ] && kill -USR1 `cat /run/nginx.pid`"
  - name: server
    path: "{{ env_server_logs }}/*.log"
    options:
      - weekly
      - size 25M
      - rotate 4
      - missingok
      - compress
      - delaycompress
      - copytruncate
  - name: supervisord
    path: "/var/log/supervisord/*.log"
    options:
      - weekly
      - size 25M
      - rotate 4
      - missingok
      - compress
      - delaycompress
      - copytruncate
firewall_allowed_tcp_ports:
  - "80"
  - "{{ env_ssh_port }}"
  - "{{ env_mysql_port }}"
