- name: cron env
  become: true
  cron:
    name: ENV_CONF_BATCH
    env: yes
    value: "{{ env_tasks_stage }}"
  tags:
    - cron
- name: cron contribution total follow task
  become: true
  cron:
      name: "contribution total follow"
      minute: "*/15"
      job: "{{ env_tasks }}/contributionTotalFollows/contributionTotalFollows >/dev/null 2>&1"
  tags:
    - cron
