- name: cron env
  become: true
  cron:
    name: ENV_CONF_BATCH
    env: yes
    value: "{{ env_tasks_stage }}"
  tags:
    - cron
- name: cron contribution total follow task
  become: true
  cron:
      name: "contribution total follow"
      minute: "*/15"
      job: "{{ env_tasks }}/contributionTotalFollows/contributionTotalFollows >/dev/null 2>&1"
  tags:
    - cron
- name: cron remove contribution file
  become: true
  cron:
      name: "remove contribution file"
      hour: "2"
      minute: "0"
      job: "{{ env_tasks }}/removeContribution/removeContribution >/dev/null 2>&1"
  tags:
    - cron
- name: cron moveTime
  become: true
  cron:
      name: "soundTime"
      hour: "2"
      minute: "0"
      job: "{{ env_tasks }}/soundTime/soundTime >/dev/null 2>&1"
  tags:
    - cron
- name: cron sitemap.xml
  become: true
  cron:
      name: "make sitemap.xml"
      hour: "2"
      minute: "0"
      job: "{{ env_tasks }}/sitemap/sitemap >/dev/null 2>&1"
  tags:
    - cron
