- name: project directory
  become: true
  file: path=/vagrant/project state=directory owner=root group=root mode=0777
- name: install go modules
  become: false
  command: go get {{ item }}
  with_items:
    - github.com/golang/lint/golint
    - golang.org/x/tools/cmd/goimports
    - github.com/nsf/gocode
    - golang.org/x/tools/cmd/gorename
    - github.com/alecthomas/gometalinter
    - github.com/zmb3/gogetdoc
    - golang.org/x/tools/cmd/godoc
    - github.com/beego/bee
    - github.com/ziutek/mymysql/godrv
    - github.com/Masterminds/glide
    - bitbucket.org/liamstask/goose/cmd/goose
    - github.com/go-xorm/dbweb
    - github.com/smartystreets/goconvey
  tags:
    - go
- name: install go modules install
  become: false
  command: go install {{ item }}
  with_items:
    - github.com/Masterminds/glide
    - github.com/go-xorm/dbweb
  tags:
    - go
- name: clone repo dotstamp_server
  become: false
  git: repo=git@github.com:wheatandcat/dotstamp_server.git dest=/vagrant/project/dotstamp_server accept_hostkey=true
  tags:
    - git
- name: clone repo dotstamp_client
  become: false
  git: repo=git@github.com:wheatandcat/dotstamp_client.git dest=/vagrant/project/dotstamp_client accept_hostkey=true
  tags:
    - git
- name: make link dotstamp_server
  become: false
  file:
    src: /vagrant/project/dotstamp_server
    dest: /home/vagrant/go/src/dotstamp_server
    state: link
  tags:
    - git
    - link
- name: make link dotstamp_server css
  become: false
  file:
    src: /vagrant/project/dotstamp_client/dist/css
    dest: /vagrant/project/dotstamp_server/static/css
    state: link
  tags:
    - git
    - link
- name: make link dotstamp_server js
  become: false
  file:
    src: /vagrant/project/dotstamp_client/dist/js
    dest: /vagrant/project/dotstamp_server/static/js
    state: link
  tags:
    - git
    - link
- name: make link dotstamp_server fonts
  become: false
  file:
    src: /vagrant/project/dotstamp_client/dist/fonts
    dest: /vagrant/project/dotstamp_server/static/fonts
    state: link
  tags:
    - git
    - link
- name: make link dotstamp_server images
  become: false
  file:
    src: /vagrant/project/dotstamp_client/dist/images
    dest: /vagrant/project/dotstamp_server/static/images
    state: link
  tags:
    - git
    - link
- name: make link dotstamp_server json
  become: false
  file:
    src: /vagrant/project/dotstamp_client/dist/json
    dest: /vagrant/project/dotstamp_server/static/json
    state: link
  tags:
    - git
    - link
- name: make link dotstamp_server txt
  become: false
  file:
    src: /vagrant/project/dotstamp_client/dist/txt
    dest: /vagrant/project/dotstamp_server/static/txt
    state: link
  tags:
    - git
    - link
- name: make dir open jtalk
  become: false
  file: path=/vagrant/project/dotstamp_server/tool/open-jtalk state=directory owner=vagrant group=root mode=0777
  tags:
    - git
    - link
- name: make dir open jtalk voice
  become: false
  file: path=/vagrant/project/dotstamp_server/tool/open-jtalk/voice state=directory owner=vagrant group=root mode=0777
  tags:
    - git
    - link
- name: make link open jtalk dic
  become: false
  file:
    src: /usr/local/share/open_jtalk/{{open_jtalk_dic_ver}}
    dest: /vagrant/project/dotstamp_server/tool/open-jtalk/dic
    state: link
  tags:
    - git
    - link
- name: make link open jtalk mei voice
  become: false
  file:
    src: /usr/local/share/hts_voice/mei
    dest: /vagrant/project/dotstamp_server/tool/open-jtalk/voice/mei
    state: link
  tags:
    - git
    - link
- name: make link open jtalk m100 voice
  become: false
  file:
    src: /usr/local/share/hts_voice/hts_voice_nitech_jp_atr503_m001-1.05/
    dest: /vagrant/project/dotstamp_server/tool/open-jtalk/voice/m100
    state: link
  tags:
    - git
    - link
