- name: project directory
  become: true
  file: path=/vagrant/project state=directory owner=root group=root mode=0777
- name: install go modules
  become: false
  command: go get {{ item }}
  with_items:
    - github.com/mattn/gom
    - github.com/pilu/fresh
    - github.com/golang/lint/golint
    - golang.org/x/tools/cmd/goimports
    - github.com/nsf/gocode
    - golang.org/x/tools/cmd/gorename
    - github.com/alecthomas/gometalinter
    - github.com/zmb3/gogetdoc
    - golang.org/x/tools/cmd/godoc
    - github.com/beego/bee
    - github.com/ziutek/mymysql/godrv
    - github.com/Masterminds/glide
    - bitbucket.org/liamstask/goose/cmd/goose
    - github.com/go-xorm/dbweb
    - github.com/smartystreets/goconvey
  tags:
    - go
- name: install go modules install
  become: false
  command: go install {{ item }}
  with_items:
    - github.com/Masterminds/glide
    - github.com/go-xorm/dbweb
  tags:
    - go
- name: clone repo dotstamp_server
  become: false
  git: repo=git@bitbucket.org:pandemo/dotstamp_server.git dest=/vagrant/project/dotstamp_server accept_hostkey=true
  tags:
    - git
- name: clone repo dotstamp_client
  become: false
  git: repo=git@bitbucket.org:pandemo/dotstamp_client.git dest=/vagrant/project/dotstamp_client accept_hostkey=true
  tags:
    - git
- name: make link dotstamp_server
  become: false
  file:
    src: /vagrant/project/dotstamp_server
    dest: /home/vagrant/go/src/dotstamp_server
    state: link
  tags:
    - git
    - link
- name: make link dotstamp_server css
  become: false
  file:
    src: /vagrant/project/dotstamp_client/dist/css
    dest: /vagrant/project/dotstamp_server/static/css
    state: link
  tags:
    - git
    - link
- name: make link dotstamp_server js
  become: false
  file:
    src: /vagrant/project/dotstamp_client/dist/js
    dest: /vagrant/project/dotstamp_server/static/js
    state: link
  tags:
    - git
    - link
- name: make link dotstamp_server fonts
  become: false
  file:
    src: /vagrant/project/dotstamp_client/dist/fonts
    dest: /vagrant/project/dotstamp_server/static/fonts
    state: link
  tags:
    - git
    - link
- name: make link dotstamp_server images
  become: false
  file:
    src: /vagrant/project/dotstamp_client/dist/images
    dest: /vagrant/project/dotstamp_server/static/images
    state: link
  tags:
    - git
    - link
- name: mysql install Mroonga
  become: false
  ignore_errors: True
  shell: mysql -ustamp -pstamp stamp -e"INSTALL PLUGIN Mroonga SONAME 'ha_mroonga.so';"
  tags:
    - mysql
- name: cron contribution total follow task
  become: true
  cron: name="contribution total follow" user=vagrant day="*" hour="*" minute="*/15" job="go run /home/vagrant/go/src/dotstamp_server/tasks/contributionTotalFollows/main.go"
  tags:
    - cron
